#!/usr/bin/perl -pi

use strict;
use warnings;

BEGIN {undef $/;}

my $humble_path = './humble.sh';
open FILE, $humble_path or die "Could not open '$humble_path'";
my $humble  = <FILE>;
close FILE;

s/_humble.*(build|package)/$humble\n$1/smg
